spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://blog-1.ckglu3iuarv2.us-east-1.rds.amazonaws.com:3306/blog?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  thymeleaf:
    cache: false
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true

logging:
  level:
    root: warn
    com.shell845.myblog: info
  file:
    name: log/blog-prod.log
server:
  port: 8080