spring:
  resources:
    add-mappings: true
  profiles:
    active: dev
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true